sudo: required
dist: trusty

language: python
python:
    - "3.4"
    - "3.5"

addons:
    apt:
        sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main'

script:
    - sudo apt-get -qq update
    - sudo apt-get --install-recommends install -y -t trusty-backports cgmanager
    - sudo cgm create all $USER
    - sudo cgm chown all $USER $(id -u $USER) $(id -g $USER)
    - cgm movepid all $USER $$
    - sudo apt-get --install-recommends install -y -t trusty-backports lxc lxc-dev
    - echo "$USER veth lxcbr0 10" | sudo tee -a /etc/lxc/lxc-usernet
    - echo "lxc.id_map = u 0 100000 65536" | sudo tee -a /etc/lxc/default.conf
    - echo "lxc.id_map = g 0 100000 65536" | sudo tee -a /etc/lxc/default.conf
    - sudo usermod --add-subuids 100000-165536 $USER
    - sudo usermod --add-subgids 100000-165536 $USER
    - cat /etc/sub?id
    - git clone https://github.com/lxc/lxc.git
    - pip install -e lxc/src/python-lxc
    - mkdir -p $HOME/.config/lxc $HOME/.local/share/lxc $HOME/.cache/lxc
    - cp /etc/lxc/default.conf $HOME/.config/lxc/
    - pwd
    - ./postgresql.py -v
