sudo: required
dist: trusty

language: python
python:
    - "3.4"
    - "3.5"

addons:
    apt:
        sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main'

before_script:
    - sudo aptitude update
    - sudo aptitude install -y -t trusty-backports uidmap
    - sudo usermod --add-subuids 100000-165536 $USER
    - sudo usermod --add-subgids 100000-165536 $USER
    - sudo aptitude install -y -t trusty-backports cgmanager
    - sudo cgm create all $USER
    - sudo cgm chown all $USER $(id -u $USER) $(id -g $USER)
    - cgm movepid all $USER $$
    - sudo aptitude install -y -t trusty-backports lxc lxc-dev
    - echo "$USER veth lxcbr0 10" | sudo tee -a /etc/lxc/lxc-usernet
    - echo "lxc.id_map = u 0 100000 65536" | sudo tee -a /etc/lxc/default.conf
    - echo "lxc.id_map = g 0 100000 65536" | sudo tee -a /etc/lxc/default.conf
    - git clone https://github.com/lxc/lxc.git
    - pip install -e lxc/src/python-lxc
    - mkdir -p $HOME/.config/lxc $HOME/.local/share/lxc $HOME/.cache/lxc
    - cp /etc/lxc/default.conf $HOME/.config/lxc/
    - sudo chmod +x $HOME
    - sudo chmod +x /var/lib/lxc
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
    - export DISPLAY=:99.0
    - export PYDEV_SCRIPT=$HOME/.local/share/lxc/test_pydev_jessie/start-pydev

script:
    - ./postgresql.py -v
    - ./django.py -v
    - ./pydev.py -v
    - timeout 30s $PYDEV_SCRIPT
